name: first
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu_latest
    steps:
      - name: Print greeting
        run: echo "Hello"
      - name: Print bye
        run: echo "Hello bye"

